stages:
  - lint
  - analyze
  - build
  - deploy

before_script:
  - apt-get update
  - apt-get install -y cppcheck clang-tidy clang git

lint:
  stage: lint
  script:
    - cppcheck --enable=all --inconclusive --std=c99 --suppress=missingIncludeSystem hello.c
  allow_failure: false
  only:
    - merge_requests
    - branches

analyze:
  stage: analyze
  script:
    - clang-tidy hello.c -- -std=c99
  allow_failure: false
  only:
    - merge_requests
    - branches

build:
  stage: build
  script:
    - gcc -o hello hello.c
  only:
    - merge_requests
    - branches

deploy:
  stage: deploy
  script:
    - git init
    - git remote add origin https://github.com/bnelford/example-project-public.git
    - git checkout -b deployment
    - git add .
    - git commit -m "Deploying code"
    - git push -f origin deployment
  environment:
    name: production
    url: https://github.com/bnelford/example-project-public
  only:
    - master
  when: manual
  allow_failure: false
